Add rhyme correctness test
pulibrary/nursery-rhyme-thanya pull request #1
Opened 2021-07-06 17:50 UTC by thanyabegum

2021-07-06 18:17 UTC, tpendragon requested changes

2021-07-06 18:17 UTC, tpendragon commented on spec/rhyme_spec.rb
> +    expect(subject).to match(rhyme_file)
Question: What is `subject` here?

2021-07-06 19:40 UTC, thanyabegum commented on spec/rhyme_spec.rb
> +    expect(subject).to match(rhyme_file)
`subject` is an instance of the Rhyme class. I implicitly defined it here. Do you think it would be more readable if I explicitly defined it?

2021-07-07 16:12 UTC, tpendragon approved these changes

2021-07-07 16:16 UTC, merged